url: http://www.millionprints.com/
baseurl: /

# Site settings
title: millionprints.com
email: bazmati@gmail.com
description: We specialized in Custom Printing on LEGO pieces, from custom projects to shopping already printed pieces.

# Team names, titles and social links
people:
    - name: Marc-André Bazergui
      pic: 1
      position: Owner/Operator
      social:
        - title: twitter
          url: https://twitter.com/mbzrg
        - title: facebook
          url: https://www.facebook.com/marc.a.bazergui
        - title: linkedin
          url: https://www.linkedin.com/in/marcandrebazergui/          

    - name: bazmarc.ca
      pic: 2
      position: MINDSTORMS Adventures
      social:
        - title: Website
          url: https://bazmarc.ca
        - title: facebook
          url: https://www.facebook.com/marc.a.bazergui
        - title: linkedin
          url: https://www.linkedin.com/in/marcandrebazergui/

    - name: Le Flag Shop Montreal
      pic: 3
      position: Official Reseller of MillionPrints
      social:
         - title: facebook
           url: https://www.facebook.com/LeFlagShopMontreal/
         - title: facebook
           url: https://www.facebook.com/marc.a.bazergui
         - title: linkedin
           url: https://www.linkedin.com/in/marcandrebazergui/
      

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/millionprints/ 
 

# Postal address (add as many lines as necessary)
address:
  - line: 214-2801 Rue du Centre
  - line: Montreal, Québec, CANADA
  - line: H3K 3C4

# Build settings
markdown: kramdown
permalink: pretty
