url: http://www.millionprints.com/
baseurl: /

# Site settings
title: millionprint.com
email: bazmati@gmail.com
description: We specialized in Custom Printing on LEGO pieces, from custom projects to shopping already printed pieces.

# Team names, titles and social links
people:
- name: Le Flag Shop Montreal
  pic: 1
  position: Bien plus que des drapeaux
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #https://www.facebook.com/LeFlagShopMontreal/
    - title: stack-overflow
      url: #

- name: Marc-André Bazergui
  pic: 2
  position: Owner/Operator
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #https://www.facebook.com/millionprints/
    - title: linkedin
      url: #

- name: bazmarc.ca
  pic: 3
  position: MINDSTORMS Adventures
  social:
    - title: twitter
      url: #
    - title: Website
      url: #https://bazmarc.ca
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: 
  - title: github
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: 214-2801 Rue du Centre
  - line: Montreal, Québec, CANADA
  - line: H3K 3C4

# Build settings
markdown: kramdown
permalink: pretty
