baseurl: 

# Site settings
title: millionprints.com
email: bazmati@gmail.com
description: We specialized in Custom Printing on LEGO pieces, from custom projects to shopping already printed pieces.

# Team names, titles and social links
people:
    - name: Marc-André Bazergui
      pic: 1
      position: Owner/Operator
      url: https://www.linkedin.com/in/marcandrebazergui/
      social:
        - title: twitter
          url: https://twitter.com/mbzrg
        - title: facebook
          url: https://www.facebook.com/marc.a.bazergui
        - title: linkedin
          url: https://www.linkedin.com/in/marcandrebazergui/          

    - name: bazmarc.ca
      pic: 2
      position: MINDSTORMS Adventures
      url: http://bazmarc.ca

    - name: Le Flag Shop Montreal
      pic: 3
      position: Official Reseller of MillionPrints
      url: https://www.facebook.com/LeFlagShopMontreal/
      

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/millionprints/ 
 

# Postal address (add as many lines as necessary)
address:
  - line: Canada

# Build settings
markdown: kramdown
permalink: pretty
